[tool.poetry]
name = "python-dupan"
version = "0.0.2.1"
description = "Python wrapper for `baidu webdisk <https://pan.baidu.com>`."
authors = ["ChenyangGao <wosiwujm@gmail.com>"]
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/ChenyangGao/web-mount-packs/tree/main/python-dupan-client"
repository = "https://github.com/ChenyangGao/web-mount-packs/tree/main/python-dupan-client"
keywords = ["nas", "dupan", "百度网盘"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.12"
ddddocr = "*"
ed2k = ">=0.0.2.1"
glob_pattern = ">=0.0.2"
http_response = ">=0.0.2.2"
httpx = "*"
httpx_request = ">=0.1.2"
lxml = "*"
multidict = "*"
orjson = "*"
python-cookietools = ">=0.0.2.1"
python-filewrap = ">=0.2.6.1"
python-hashtools = ">=0.0.3.3"
python-httpfile = ">=0.0.5"
python-iterutils = ">=0.2.4.1"
python-property = ">=0.0.3"
python-startfile = ">=0.0.2"
python-texttools = ">=0.0.3"
qrcode = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.packages]]
include = "dupan"
